// eslint-disable-next-line import/no-extraneous-dependencies
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation";
import CustomProvider from "@/provider";
import React from "react";
import "./globals.css";

// import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

// const inter = Inter({ subsets: ["latin"] });

/* Static metadata  */
export const metadata: Metadata = {
    title: {
        /* used to provide a fallback title to child route segments that don't define a title. */
        default: "Nextjs",
        /* used to add a prefix or a suffix to titles defined in child route segments. */
        template: "%s | Acme",
        /* used to provide a title that ignores title.template set in parent segments. */
        // absolute: "",
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <header className="bg-slate-300">header</header>
                <CustomProvider>
                    <Navigation />
                    <AntdRegistry>{children}</AntdRegistry>
                </CustomProvider>
                <footer className="bg-slate-300 fixed bottom-0 w-full">
                    Footer
                </footer>
            </body>
        </html>
    );
}
