import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation";
import CustomProvider from "@/provider";
import React from "react";
import "./globals.css";

// import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <header className="bg-slate-300">header</header>
                <CustomProvider>
                    <Navigation />
                    <div>{children}</div>
                </CustomProvider>
                <footer className="bg-slate-300">Footer</footer>
            </body>
        </html>
    );
}
